#Minecraft server properties
#Tue Nov 18 01:54:12 UTC 2025
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=cristellib\:runtime_pack
initial-enabled-packs=vanilla,fabric,accessories,adventuredungeons,aether,aether_villages,archers,armory_rpgs,arsenal,awesomedungeon,awesomedungeonocean,balm,berserker_rpg,bettercaves,bettercombat,betterdeserttemples,betterdungeons,betterendisland,betterfortresses,betterjungletemples,bettermineshafts,betteroceanmonuments,betterwitchhuts,bookshelf,bosses_of_mass_destruction,brutalbosses,carryon,collective,combat_roll,creeperoverhaul,critical_strike,darkbosses,dungeon_difficulty,dungeons_arise,dungeons_arise_seven_seas,easyanvils,ecologics,eldritch_mobs,elemental_wizards_rpg,explorify,fabric-convention-tags-v2,fastitemframes,formidulus,ftbessentials,gazebo,geophilic,globalxp,hopobetterunderwaterruins,illagerinvasion,immersivelanterns,jewelry,libraryferret,lithostitched,lne_archers,lne_paladins,lne_rogues,lne_wizards,loot_n_explore,lootintegrations,lootintegrations_yungs,medievalend,minecells,moonlight,more_relics,more_rpg_classes,mr_dungeons_andtaverns,mr_dungeons_andtavernsancientcityoverhaul,mr_dungeons_andtavernsendcastlestandalone,mr_dungeons_andtavernspillageroutpostoverhaul,mr_dungeons_andtavernsstrongholdoverhaul,mr_dungeons_andtavernswoodlandmansionreplacement,mrpgc_skill_tree,mss,mvs,paladins,relics_rpgs,rightclickharvest,rogues,runes,server_translations_api,skill_tree_rpgs,smallships,spell_engine,spell_power,supermartijn642corelib,t_and_t,takesapillage,terrablender,terralith,the_bumblezone,tinyskeletons,travelersbackpack,trinkets,u_sea,village_taverns,waystones,witcher_rpg,wizards,yigd,yungsapi,yungsbridges,yungscavebiomes,yungsextras,elemental_wizards_rpg\:wizard_changes,mrpgc_skill_tree\:mrpgc_skill_tree_changes,spell_engine\:trinkets_compat,mrpgc_skill_tree\:mrpgc_skill_tree_changes,t_and_t\:resources/t_and_t_waystones_patch
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=1
max-tick-time=60000
max-world-size=29999984
motd=a
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
